#!/bin/bash

# Import Collections to PocketBase via browsermcp/manual or API

echo "📦 Creating CloudFreedom Collections in PocketBase..."
echo ""
echo "Collections needed:"
echo "  - tenants"
echo "  - products" 
echo "  - provider_keys"
echo "  - usage_logs"
echo ""
echo "⚠️  PocketBase 0.30.2 hat keinen CLI Import Command."
echo "Du musst sie manuell über die UI erstellen:"
echo ""
echo "1. Gehe zu: http://localhost:9200/_/#/collections"
echo "2. Klicke auf '+ New collection'"
echo "3. Erstelle für jede Collection:"
echo ""
echo "=== TENANTS ==="
echo "Name: tenants"
echo "Fields:"
echo "  - name (text, required)"
echo "  - slug (text, required)"
echo "  - domain (text)"
echo "  - type (select: internal,demo,public,enterprise,dev)"
echo "  - status (select: active,inactive,pending)"
echo ""
echo "=== PRODUCTS ==="
echo "Name: products"  
echo "Fields:"
echo "  - name (text, required)"
echo "  - price (number, required)"
echo "  - budget (number, required)"
echo "  - description (text)"
echo ""
echo "=== PROVIDER_KEYS ==="
echo "Name: provider_keys"
echo "Fields:"
echo "  - provider (select: google,azure,aws,anthropic,openai)"
echo "  - api_key (text, required)"
echo "  - budget_limit (number)"
echo "  - status (select: active,inactive)"
echo ""
echo "Oder nutze: http://localhost:9200/_/ → Settings → Import Collections"
echo "Datei: collections_complete_with_new.json"
